# Generated by Django 5.2 on 2025-05-06 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_populate_achievements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_template', models.TextField(help_text="Template for challenge description, e.g., 'Complete {target_value} lessons today.'")),
                ('challenge_type', models.CharField(choices=[('COMPLETE_N_LESSONS', 'Complete N Lessons'), ('EARN_N_POINTS', 'Earn N Points'), ('COMPLETE_PROJECT', 'Complete any Project')], max_length=50)),
                ('target_value', models.IntegerField(default=1)),
                ('points_reward', models.IntegerField(default=20, help_text='Bonus points for completing the daily challenge.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this challenge type can be assigned.')),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('current_progress', models.IntegerField(default=0)),
                ('initial_points_at_assignment', models.IntegerField(blank=True, default=0, null=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.dailychallenge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_instance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
