# Generated by Django 5.2 on 2025-05-06 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_populate_daily_challenge_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('system', 'System Default'), ('light', 'Light Mode'), ('dark', 'Dark Mode')], default='system', help_text='Select your preferred theme for the application.', max_length=10)),
                ('notify_daily_challenge_email', models.BooleanField(default=True, help_text='Receive an email when a new daily challenge is available.')),
                ('notify_streak_risk_email', models.BooleanField(default=True, help_text='Receive an email reminder if your activity streak is at risk.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
