# Generated by Django 5.2 on 2025-05-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_userprofile_receive_email_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='receive_email_notifications',
        ),
    ]
